### ISSUE TITLE
pycricket_storagehandler does not get installed

### ISSUE THREAD

**Issue by kunalg** [roanuz/py-cricket#1]
[pycricket.py imports pycricket_storagehandler](https://github.com/roanuz/py-cricket/blob/master/pycricket.py#L26), but [setup.py does not install pycricket_storagehandler.py](https://github.com/roanuz/py-cricket/blob/master/setup.py#L10)

That line in setup.py should read as:

``` python
py_modules=['pycricket', 'pycricket_storagehandler'],
```

**Comment by Rajeev69** [comment]
Can you try with the following code,

import pycricket
handler = pycricket.RcaStorageHandler()
start = pycricket.RcaApp("Your_AccessKey", \
                        "Your_ScreteKey", \
                        "Your_APP_ID", \
                        handler
                       )

**Comment by kunalg** [comment]
The import itself fails:

``` python
(pycricket)kunal@hydrogen:~/work/my_work/python/pycricket$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycricket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kunal/work/my_work/python/pycricket/local/lib/python2.7/site-packages/pycricket.py", line 26, in <module>
    from pycricket_storagehandler import *
ImportError: No module named pycricket_storagehandler
>>> 
```

**Comment by kunalg** [comment]
I installed pycricket using pip from github:

``` python
(pycricket)kunal@hydrogen:~/work/my_work/python/pycricket$ pip install git+https://github.com/roanuz/py-cricket#egg=pycricket
```

Cannot install with simple `pip install py-cricket` since it's not available on pypi.

**Comment by Rajeev69** [comment]
Yes, there is mistake in setup.py file. I will make sure, its fixed soon. Could you please tell me what error you are getting when you try to install 'pip install py-cricket'

**Comment by kunalg** [comment]
whoops, it seems to be working now. Just tried `pip install py-cricket` in a new virtenv - seems to work perfect - including pycricket_storagehandler.

For some reason it didn't work last night :(

**Comment by Rajeev69** [comment]
Nice :+1:
